CREATE TABLE sales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_assistant varchar(255),
  time_stamp varchar(255),
  till_id varchar(255)
);
CREATE INDEX sales_assistant ON sales(sales_assistant);